# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: SparkSketch-Staging Web App

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true


      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 7.0.7

      - name: Add dotnet tools to PATH
        run: |
          echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Set SQL connection string
        run: echo "SQL_CONNECTION_STRING=${{ secrets.SQL_CONNECTION_STRING_STAGING }}" >> $GITHUB_ENV

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./backend

      - name: Create migration SQL script
        run: dotnet ef migrations script -o migration.sql --connection "${{ secrets.SQL_CONNECTION_STRING_STAGING }}" --context SparkSketchContext
        working-directory: ./backend

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: ./backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Upload migration SQL script
        uses: actions/upload-artifact@v3
        with:
          name: migration-script
          path: ./backend/migration.sql

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Download migration script from build job
        uses: actions/download-artifact@v3
        with:
          name: migration-script
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A101247A628D43EC96BF3172F5F47BB5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA802CFC82D143558A0C2C81FCEACF11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C0D868433A334523885AC295305D96C6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SparkSketch-Staging'
          slot-name: 'Production'
          package: .
          
      - name: Run migration script on Azure SQL Database
        env:
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE_STAGING }}
          AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
        run: |
          sqlcmd -S $AZURE_SQL_SERVER.database.windows.net -d $AZURE_SQL_DATABASE -U $AZURE_SQL_USERNAME -P $AZURE_SQL_PASSWORD -i migration.sql
